package com.example.tasktracker001.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a Task in the application.
 *
 * @property id Unique ID for the task, auto-generated by Room.
 * @property title The main title or name of the task.
 * @property description A detailed explanation of the work to be done.
 * @property isCompleted Status flag indicating if the task is finished.
 * @property dueDate Optional deadline for the task as a timestamp.
 * @property priority The urgency level of the task.
 * @property assignedToUserId The ID of the user responsible for this task.
 * @property projectId The ID of the project this task belongs to.
 * @property attachments List of file paths or URIs associated with the task.
 * @property timeSpent Total time recorded on this task in milliseconds.
 */
@Entity(tableName = "tasks")
data class Task(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val description: String,
    val isCompleted: Boolean = false,
    val dueDate: Long? = null,
    val priority: Priority = Priority.MEDIUM,
    val assignedToUserId: Int? = null,
    val projectId: Int? = null,
    val attachments: List<String> = emptyList(),
    val timeSpent: Long = 0L
)